### ISSUE TITLE
Move Binary Type Checks to Annotations

### ISSUE THREAD

**Issue by yuanzexiong** [HectorPeeters/fontoxpath#12]
# Description

The type checking of the binary operators should be moved to the annotation phase, so that in most cases this does not need to happen during runtime.
In case no type could be inferred, dynamic type checking should be used as a fallback, so the original type checking code should not be removed completely.

# Sub-tasks

Addition (a+b)
- [ ] Move type checks to annotion step.
- [ ] Make sure that corresponding tests pass.

Subtraction (a-b)
- [ ] Move type checks to annotion step.
- [ ] Make sure that corresponding tests pass.

Multiplication (a*b)
- [ ] Move type checks to annotion step.
- [ ] Make sure that corresponding tests pass.

Division (a/b)
- [ ] Move type checks to annotion step.
- [ ] Make sure that corresponding tests pass.

Integer division (a idiv b)
- [ ] Move type checks to annotion step.
- [ ] Make sure that corresponding tests pass.

Modulus (a % b)
- [x] Move type checks to annotion step.
- [ ] Make sure that corresponding tests pass.

General:
- [ ] Insert early return path to binaryOperators file if type inference was successful.
