### ISSUE TITLE
Speedup Subtype Check

### ISSUE THREAD

**Issue by MTimmerije** [HectorPeeters/fontoxpath#13]
# Description

The `isSubtypeOf` check is currently a recursive function that's not the fastest. This can be sped up a bit (making it O(1)) by taking the current types, calling `isSubtypeOf` over all pairs of types and adding the true pairs into a set. This set could then be checked against with O(1) complexity. 

Potentially this set can be cached to reduce overhead on application start, as the set should be a relatively small subset of all type combinations and the set creation is O(n^2)

This task is quite low priority and should only be implemented when we have time after implementing the rest, as it's nicely separated (it only requires changes within the `isSubtypeOf` function) and not fundamental for our project.

# Sub-tasks

- [x] Create a set that contains all type tuples (a,b) for which `isSubtypeOf` returns true.
- [x] Replace the original isSubtypeOf function with a query on this set.
- [x] (Optional) Caching the set to the disk, to avoid the intial set creation.
- [x] Benchmarking to see if there is a noticeable performance improvement.

**Comment by MTimmerije** [comment]
To be clear, this is a bit of an optional task. 
It should only be implemented after we did a bunch of the other stuff.
So it's very much "when we get around to it".

**Comment by MTimmerije** [comment]
No notice-able performance improvement, so closing this.
