### ISSUE TITLE
Final version of report

### ISSUE THREAD

**Issue by FBroy** [HectorPeeters/fontoxpath#160]
# Description

As we finalise the report, the whole team should proof-read every section to make sure the text makes sense and fits.
We should also spell-check every section in the report with Grammarly or similar tools.
When everyone in the team approves, we can mark a section as finalised.

## Extra info:

[https://brightspace.tudelft.nl/d2l/common/dialogs/quickLink/quickLink.d2l?ou=281758&type=content&rcode=tudelft-660804](Rubric)
[https://brightspace.tudelft.nl/d2l/lms/dropbox/user/folder_submit_files.d2l?db=74385&grpid=384312&isprv=0&bp=0&ou=281758](Brightspace Assignment)
[https://repository.tudelft.nl/islandora/search/?collection=education](Examples)

# Sub-tasks

## Proof-reading

Frank:
- [x] Preface
- [x] Summary
- [x] Table of Contents
- [x] Introduction (Chapter 1)
- [x] Performance Problem Analysis (Chapter 2)
- [x] Requirements for Type Inference (Chapter 3)
- [x] Project Methodologies (Chapter 4)
- [x] Improvements on the original Implementation (Chapter 5)
- [x] Timeline (Chapter 6)
- [x] Project Retrospect (Chapter 7)
- [x] Conclusion (Chapter 8)
- [x] References
- [x] Appendix A (Project description by Fonto)
- [x] Appendix B (Type Inference)

Palle:
- [x] Preface
- [x] Summary
- [x] Table of Contents
- [x] Introduction (Chapter 1)
- [x] Performance Problem Analysis (Chapter 2)
- [x] Requirements for Type Inference (Chapter 3)
- [x] Project Methodologies (Chapter 4)
- [x] Improvements on the original Implementation (Chapter 5)
- [x] Timeline (Chapter 6)
- [ ] Project Retrospect (Chapter 7)
- [ ] Conclusion (Chapter 8)
- [ ] References
- [x] Appendix A (Project description by Fonto)
- [x] Appendix B (Type Inference)

Hector:
- [x] Preface
- [x] Summary
- [x] Table of Contents
- [x] Introduction (Chapter 1)
- [x] Performance Problem Analysis (Chapter 2)
- [x] Requirements for Type Inference (Chapter 3)
- [x] Project Methodologies (Chapter 4)
- [x] Improvements on the original Implementation (Chapter 5)
- [x] Timeline (Chapter 6)
- [x] Project Retrospect (Chapter 7)
- [ ] Conclusion (Chapter 8)
- [ ] References
- [x] Appendix A (Project description by Fonto)
- [x] Appendix B (Type Inference)

Marijn:
- [x] Preface
- [x] Summary
- [x] Table of Contents
- [x] Introduction (Chapter 1)
- [x] Performance Problem Analysis (Chapter 2)
- [ ] Requirements for Type Inference (Chapter 3)
- [ ] Project Methodologies (Chapter 4)
- [ ] Improvements on the original Implementation (Chapter 5)
- [ ] Timeline (Chapter 6)
- [ ] Project Retrospect (Chapter 7)
- [ ] Conclusion (Chapter 8)
- [ ] References
- [ ] Appendix A (Project description by Fonto)
- [ ] Appendix B (Type Inference)

Vincent:
- [x] Preface
- [x] Summary
- [x] Table of Contents
- [x] Introduction (Chapter 1)
- [x] Performance Problem Analysis (Chapter 2)
- [x] Requirements for Type Inference (Chapter 3)
- [x] Project Methodologies (Chapter 4)
- [x] Improvements on the original Implementation (Chapter 5)
- [ ] Timeline (Chapter 6)
- [ ] Project Retrospect (Chapter 7)
- [ ] Conclusion (Chapter 8)
- [ ] References
- [ ] Appendix A (Project description by Fonto)
- [ ] Appendix B (Type Inference)

## Spell checking (Can only be checked when it has been proof-read by everyone in the team)

- [x] Preface
- [x] Summary
- [x] Table of Contents
- [x] Introduction (Chapter 1)
- [x] Performance Problem Analysis (Chapter 2)
- [x] Requirements for Type Inference (Chapter 3)
- [x] Project Methodologies (Chapter 4)
- [x] Improvements on the original Implementation (Chapter 5)
- [x] Timeline (Chapter 6)
- [x] Project Retrospect (Chapter 7)
- [x] Conclusion (Chapter 8)
- [x] References
- [x] Appendix A (Project description by Fonto)
- [x] Appendix B (Type Inference)
