### ISSUE TITLE
Fix the bininary Operator annotation

### ISSUE THREAD

**Issue by maanpalle** [HectorPeeters/fontoxpath#38]
# Description

Fix the bininary Operator annotation by using the checks made by fonto in binaryoperator.ts

# Sub-tasks

Atomized tasks that cannot be broken down further.

- [x] Copy the code
- [x] Trefactor to the point it works with our implementation
- [x] Fix the non-working tests
