### ISSUE TITLE
Cleanup binary operator

### ISSUE THREAD

**Issue by maanpalle** [HectorPeeters/fontoxpath#40]
# Description

The binary operator annotation at this moment is code copied straight out of binary operator this needs to be fixed.

# Sub-tasks

- [x] Find a better way to make it more compact
- [x] Make it beautiful
- [x] Fix the tests
