### ISSUE TITLE
Annotation Cast Operator and Castable Operator

### ISSUE THREAD

**Issue by yuanzexiong** [HectorPeeters/fontoxpath#43]
## Description

Cast operators need to be converted in roughly the same style as the binary operator.

## Sub-tasks

- [x] Lookup the casts
- [x] Copy the ruleset of each cast
- [x] Paste them in annotation
- [x] Tests (for new behaviour)
