### ISSUE TITLE
Add type annotation for all the AST nodes

### ISSUE THREAD

**Issue by HectorPeeters** [HectorPeeters/fontoxpath#58]
# Description

At the end of the project, we should have the type annotation implemented for many of the AST nodes  as possible.

# Sub-tasks

- [x] andOp
- [x] orOp
- [x] unaryPlusOp
- [x] unaryMinusOp
- [x] addOp
- [x] subtractOp
- [x] multiplyOp
- [x] divOp
- [x] idivOp
- [x] modOp
- [x] sequenceExpr
- [x] unionOp
- [x] exceptOp
- [x] intersectOp
- [x] stringConcatenateOp
- [x] rangeSequenceExpr
- [x] equalOp
- [x] notEqualOp
- [x] lessThanOrEqualOp
- [x] lessThanOp
- [x] greaterThanOrEqualOp
- [x] greaterThanOp
- [x] eqOp
- [x] neOp
- [x] ltOp
- [x] leOp
- [x] gtOp
- [x] geOp
- [x] isOp
- [x] nodeBeforeOp
- [x] nodeAfterOp
- [x] pathExpr
- [x] contextItemExpr
- [x] functionCallExpr
- [x] inlineFunctionExpr (Halted by scope / static context)
- [x] arrowExpr (Halted by scope / static context)
- [x] dynamicFunctionInvocationExpr (`undefined`: Cannot be determined, needs to run XPath)
- [x] namedFunctionRef (Halted by scope)
- [x] intergerConstantExpr
- [x] stringConstantExpr
- [x] decimalConstantExpr
- [x] doubleConstantExpr
- [x] quantifiedExpr 
- [x] ifThenElseExpr
- [x] instanceOfExpr
- [x] castExpr
- [x] castableExpr
- [x] simpleMapExpr
- [x] mapConstructor
- [x] arrayConstructor
- [x] unaryLookup
- [x] typeswitchExpr

**Comment by MTimmerije** [comment]
Removed the FLWOR and VarRef expressions and moved them to their own issues. #88 and #89

**Comment by MTimmerije** [comment]
All subtasks are done or spliced off into their own issues.
