### ISSUE TITLE
Integrate Type Inference into Binary Operator

### ISSUE THREAD

**Issue by MTimmerije** [HectorPeeters/fontoxpath#6]
# Issue

## Description

We have to integrate the type inference into the binary operator. This is done by taking out the type checks from the binaryoperator class and moving them to a separate function that embeds the types directly into the AST.

## Sub-tasks

- [ ] Modify the AST after parsing with type annotations.
- [ ] (Re)move type checking logic from the BinaryOperator class
- [ ] Make sure tests still run
