### ISSUE TITLE
Split up binary generateBinaryOperatorFunction in 2 different functions

### ISSUE THREAD

**Issue by maanpalle** [HectorPeeters/fontoxpath#60]
# Description

At the moment we have 2 different maps but they still are used in the same place we need to split up functions so they only return relevant information

# Sub-tasks

- [x] split up generateBinaryOperatorFunction 
- [x] Go over everything and use the relevant functions
- [x] Fix the tests
- [x] Move the BinaryEvaluationFunction type definition out of it's own file, it feels a bit lonely there
