### ISSUE TITLE
Write tests for the annotation of the tree

### ISSUE THREAD

**Issue by maanpalle** [HectorPeeters/fontoxpath#61]
# Description

Write tests for the annotation of the AST.

# Sub-tasks

- [x] Make assertion function
- [x] Add unary op tests
- [x] Add binop tests
- [x] Add cast tests
- [x] Add comparison tests
