### ISSUE TITLE
Convert annotateAst to visitor pattern

### ISSUE THREAD

**Issue by HectorPeeters** [HectorPeeters/fontoxpath#63]
# Description

Right now, the AST gets traversed manually using recursive switch statements and this happens multiple times throughout the codebase, it would probably be cleaner if we make a single AstVisitor class which can be used in both annotateAst and compileAstToExpression.

# Sub-tasks

- [ ] Construct an AstVisitor class
- [ ] Convert annotateAst to use this class
- [ ] Potentially also convert compileAstToExpression

**Comment by HectorPeeters** [comment]
The current implementation added a 2% performance decrease so for now this isn't a good solution.
