### ISSUE TITLE
Failing XML tests

### ISSUE THREAD

**Issue by HectorPeeters** [HectorPeeters/fontoxpath#7]
# Description

Since the structure of the IAST has been changed, tests that assert the intermediate AST will fail. This can be fixed by either changing the test assertions, or by not executing the type inference step when running these tests.

# Sub-tasks

- [x] Add a flag to to parseExpression which determines if the AST should be annotated
- [x] Propagate this change through the rest of the codebase
- [x] Make the tests which assert the AST structure not use type-inference
