### ISSUE TITLE
VarRef Type Annotation

### ISSUE THREAD

**Issue by MTimmerije** [HectorPeeters/fontoxpath#88]
# Description

Create annotations for VarRef expressions and integrate them into the AST
These are currently locked behind some changes to the static context and the scoping

# Sub-tasks

- [ ] Implement Type Annotation for the VarRef expression
- [ ] Integrate them into the AST
- [ ] Create Tests to make sure coverage does not drop

**Comment by MTimmerije** [comment]
Please tick off which things you've implemented, or if it's done entirely, close the issue.
