### ISSUE TITLE
FLWOR Expression Type Annotation

### ISSUE THREAD

**Issue by MTimmerije** [HectorPeeters/fontoxpath#89]
# Description

Create annotations for FLWOR (For Let While Order Return) expressions and integrate them into the AST.
These are currently locked behind some changes to the static context and the scoping

# Sub-tasks

- [ ] Implement Type Annotation for the FLWOR expression
- [ ] Integrate them into the AST
- [ ] Create Tests to make sure coverage does not drop
