### ISSUE TITLE
Move Unary Type Check to Annotation

### ISSUE THREAD

**Issue by MTimmerije** [HectorPeeters/fontoxpath#9]
# Description

The unary type now does a dynamic check for its type, this can be done during the AST annotation phase, so it should be moved there.

# Sub-tasks

Plus
- [x] Migrate type check to annotation and embed it into the AST
- [x] In the original Unary file, check the annotation and fall back on doing it dynamically if there is no annotation.

Minus (negation)
- [x] Migrate type check to annotation and embed it into the AST
- [x] In the original Unary file, check the annotation and fall back on doing it dynamically if there is no annotation.
