### ISSUE TITLE
Create Coverage Metric to Measure Annotation

### ISSUE THREAD

**Issue by MTimmerije** [HectorPeeters/fontoxpath#93]
# Description

We want to know how well our implementation covers the queries, we want to keep track of how many annotations are made for a given query. A simple metric would be: annotations/nodes for a query.

# Sub-tasks

- [x] Keep track of the annotation number as well as the total nodes in an AST
- [x] Get a way to get the metric after annotating
- [x] Find a way to properly display the metric
