### ISSUE TITLE
Create/Fix Built in Function Call Annotation

### ISSUE THREAD

**Issue by MTimmerije** [HectorPeeters/fontoxpath#95]
# Description

Built in Functions are not getting annotated, that needs to be fixed.

# Sub-tasks

- [x] Make sure function calls get annotated appropriately.
- [x] Make sure arrow expressions get annotated appropriately.
- [x] Make sure Path Expressions get annotated appropriately.
